version: 2.1
jobs:

  build_docker:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t proofofwork/powco.dev:$CIRCLE_BRANCH . 
      - run:
          name: Build docker image
          command: cd web-ui && docker build -t proofofwork/powco.dev-webui:$CIRCLE_BRANCH . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
            docker push proofofwork/powco.dev:$CIRCLE_BRANCH
            docker push proofofwork/powco.dev-webui:$CIRCLE_BRANCH

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker
